### ISSUE TITLE
Own translations get overwritten

### ISSUE THREAD

**Issue by matthijsgroen** [carrierwaveuploader/carrierwave#1055]
I want to set my own translation messages in my project.

When I define in Rails the following `config/locales/en.yml`

``` yaml

en:
  errors:
    messages:
      extension_white_list_error: 'foobar'

```

in the same fashion as https://github.com/jnicklas/carrierwave/blob/master/lib/carrierwave/locale/en.yml

When you run the rails console and execute `I18n.t 'errors.messages.extension_white_list_error'` you will get:

``` sh
=> "You are not allowed to upload %{extension} files, allowed types: %{allowed_types}"
```

should the output not be: `foobar`?
