### ISSUE TITLE
Custom locales are ignored…

### ISSUE THREAD

**Issue by ream88** [carrierwaveuploader/carrierwave#1188]
Though I'm using the recommended way to translate the error messages:

``` yaml
en:
  errors:
    messages:
      extension_white_list_error: does not allow .%{extension} files
```

CarrierWave does completely ignore them and uses the build-in message: 

```
"You are not allowed to upload %{extension} files, allowed types: %{allowed_types}"
```

Any idea what could possible go wrong?
