### ISSUE TITLE
Deserializing is affecting url of uploaded file

### ISSUE THREAD

**Issue by donatoaz** [carrierwaveuploader/carrierwave#2370]
Hi guys,

I have a model that is versioned using [paper_trail](https://github.com/paper-trail-gem/paper_trail) and this model has a mounted carrierwave attribute. I  am having the following issue:

When I restore (reify in paper_trail terms) a previous version of a given model instance, and access the url attribute it gives me:

```
irb(main):015:0> svo.before_image.url
=> "https://mybucket.s3.amazonaws.com/uploads/servicing/before_image/260826/https%3A//mybucket.s3.amazonaws.com/uploads/servicing/before_image/260826/c7aee1dc1aa953300bd29c2f7af1c432add8d75d.jpeg"
```

whereas it should be simply `https://mybucket.s3.amazonaws.com/uploads/servicing/before_image/260826/c7aee1dc1aa953300bd29c2f7af1c432add8d75d.jpeg`

I suppose it might have something to do with deserialization (thus why I am posting this here and not on the paper_trail repo). My model instance is being serialized and stored as such on the database, take note of the `before_image` and `after_image` attrs that are mounts:

Also, any tips as to how to optimize how this should be serialized/deserialized (because it seems there is plenty of redundant info on the serialized object below) is very welcomed.

Thanks!

```
irb(main):014:0> puts sv.object
---
id: 260826
status: completed
approval_status: approved
approving_user_id: 164
approving_user_name: Lloyd Montaque
approved_at: &4 2019-01-16 13:53:58.087899813 Z
before_image: &15 !ruby/object:PersistentImageUploader
  model: &17 !ruby/object:Servicing
    raw_attributes:
      id: 260826
      status: completed
      approval_status: approved
      approving_user_id: 164
      approving_user_name: Lloyd Montaque
      approved_at: &3 2019-01-16 13:53:58.087899813 Z
      before_image: c7aee1dc1aa953300bd29c2f7af1c432add8d75d.jpeg
      after_image: 403c5f98912022afe636d6b31cc2b93bb2358d40.jpeg
      work_order_id: 9588
      area_id: 20730
      high_priority: false
      completed_at: &6 2019-01-16 07:30:26.560881000 Z
      created_at: &10 2019-01-15 22:34:07.613280000 Z
      updated_at: &12 2019-01-16 13:53:58.103057262 Z
      assignee_id: 228
      claimed_by_id:
      completed_by_id: 228
      occupied_at:
      deleted_at:
      redone: false
      unable_reason:
      redo_reason:
      require_images: true
    attributes: !ruby/object:ActiveRecord::AttributeSet
      attributes:
        id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: id
          value_before_type_cast: 260826
          type: &2 !ruby/object:ActiveModel::Type::Integer
            precision:
            scale:
            limit:
            range: !ruby/range
              begin: -2147483648
              end: 2147483648
              excl: true
          original_attribute:
          value: 260826
        status: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: status
          value_before_type_cast: completed
          type: !ruby/object:ActiveRecord::Enum::EnumType
            name: :status
            mapping: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
              open: open
              in_progress: in_progress
              completed: completed
              unable: unable
              temporarily_occupied: temporarily_occupied
              permanently_occupied: permanently_occupied
            subtype: &1 !ruby/object:ActiveModel::Type::String
              precision:
              scale:
              limit:
          original_attribute:
          value: completed
        approval_status: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: approval_status
          value_before_type_cast: approved
          type: !ruby/object:ActiveRecord::Enum::EnumType
            name: :approval_status
            mapping: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
              approved: approved
              denied: denied
              rescheduled: rescheduled
            subtype: *1
          original_attribute:
          value: approved
        approving_user_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: approving_user_id
          value_before_type_cast: 164
          type: *2
          original_attribute:
          value: 164
        approving_user_name: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: approving_user_name
          value_before_type_cast: Lloyd Montaque
          type: *1
          original_attribute:
          value: Lloyd Montaque
        approved_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: approved_at
          value_before_type_cast: *3
          type: !ruby/marshalable:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
            :__v2__: []
            []: &7 !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQL::OID::DateTime
              precision:
              scale:
              limit:
          original_attribute:
          value: !ruby/object:ActiveSupport::TimeWithZone
            utc: *4
            zone: &8 !ruby/object:ActiveSupport::TimeZone
              name: Etc/UTC
            time: *4
        before_image: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: before_image
          value_before_type_cast: c7aee1dc1aa953300bd29c2f7af1c432add8d75d.jpeg
          type: &5 !ruby/object:ActiveModel::Type::Text
            precision:
            scale:
            limit:
          original_attribute:
          value: c7aee1dc1aa953300bd29c2f7af1c432add8d75d.jpeg
        after_image: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: after_image
          value_before_type_cast: 403c5f98912022afe636d6b31cc2b93bb2358d40.jpeg
          type: *5
          original_attribute:
          value: 403c5f98912022afe636d6b31cc2b93bb2358d40.jpeg
        work_order_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: work_order_id
          value_before_type_cast: 9588
          type: *2
          original_attribute:
          value: 9588
        area_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: area_id
          value_before_type_cast: 20730
          type: *2
          original_attribute:
          value: 20730
        high_priority: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: high_priority
          value_before_type_cast: false
          type: &14 !ruby/object:ActiveModel::Type::Boolean
            precision:
            scale:
            limit:
          original_attribute:
          value: false
        completed_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: completed_at
          value_before_type_cast: *6
          type: !ruby/marshalable:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
            :__v2__: []
            []: *7
          original_attribute:
          value: !ruby/object:ActiveSupport::TimeWithZone
            utc: &9 2019-01-16 07:30:26.560881000 Z
            zone: *8
            time: *9
        created_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: created_at
          value_before_type_cast: *10
          type: !ruby/marshalable:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
            :__v2__: []
            []: *7
          original_attribute:
          value: !ruby/object:ActiveSupport::TimeWithZone
            utc: &11 2019-01-15 22:34:07.613280000 Z
            zone: *8
            time: *11
        updated_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: updated_at
          value_before_type_cast: *12
          type: !ruby/marshalable:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
            :__v2__: []
            []: *7
          original_attribute:
          value: !ruby/object:ActiveSupport::TimeWithZone
            utc: &13 2019-01-16 13:53:58.103057262 Z
            zone: *8
            time: *13
        assignee_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: assignee_id
          value_before_type_cast: 228
          type: *2
          original_attribute:
          value: 228
        claimed_by_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: claimed_by_id
          value_before_type_cast:
          type: *2
          original_attribute:
          value:
        completed_by_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: completed_by_id
          value_before_type_cast: 228
          type: *2
          original_attribute:
          value: 228
        occupied_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: occupied_at
          value_before_type_cast:
          type: !ruby/marshalable:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
            :__v2__: []
            []: *7
          original_attribute:
          value:
        deleted_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: deleted_at
          value_before_type_cast:
          type: !ruby/marshalable:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
            :__v2__: []
            []: *7
          original_attribute:
          value:
        redone: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: redone
          value_before_type_cast: false
          type: *14
          original_attribute:
          value: false
        unable_reason: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: unable_reason
          value_before_type_cast:
          type: *1
          original_attribute:
          value:
        redo_reason: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: redo_reason
          value_before_type_cast:
          type: *1
          original_attribute:
          value:
        require_images: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: require_images
          value_before_type_cast: true
          type: *14
          original_attribute:
          value: true
    new_record: false
    active_record_yaml_version: 1
  mounted_as: :before_image
  file: !ruby/object:CarrierWave::Storage::Fog::File
    uploader: *15
    base: &16 !ruby/object:CarrierWave::Storage::Fog
      uploader: *15
    path: uploads/servicing/before_image/260826/c7aee1dc1aa953300bd29c2f7af1c432add8d75d.jpeg
    content_type:
  filename:
  cache_id:
  versions: {}
  format:
  storage: *16
after_image: &18 !ruby/object:PersistentImageUploader
  model: *17
  mounted_as: :after_image
  file: !ruby/object:CarrierWave::Storage::Fog::File
    uploader: *18
    base: &19 !ruby/object:CarrierWave::Storage::Fog
      uploader: *18
    path: uploads/servicing/after_image/260826/403c5f98912022afe636d6b31cc2b93bb2358d40.jpeg
    content_type:
  filename:
  cache_id:
  versions: {}
  format:
  storage: *19
work_order_id: 9588
area_id: 20730
high_priority: false
completed_at: *9
created_at: *11
updated_at: *13
assignee_id: 228
claimed_by_id:
completed_by_id: 228
occupied_at:
deleted_at:
redone: false
unable_reason:
redo_reason:
require_images: true
```
