### ISSUE TITLE
Error updating ActiveRecord model after calling recreate_versions!

### ISSUE THREAD

**Issue by alexdunae** [carrierwaveuploader/carrierwave#2655]
I've think I've come across a bug in 3.0.0.beta.

It can be triggered by adding this spec to `activerecord_spec.rb`:

```ruby
it "should update attributes after recreating versions a file" do
  @event.update!(image: stub_file('test.jpeg'))
  @event.reload
  @event.image.recreate_versions!
  @event.update_attribute :foo, "something"
end
```

This passes in https://github.com/carrierwaveuploader/carrierwave/commit/6574a8fd6752b4bebc407f73cd830eac67e314af but fails in the following commit https://github.com/carrierwaveuploader/carrierwave/commit/a67bfb696dcba14c7cdfa2c1b5481f04d3ef8dae

With an error like:

```
  1) CarrierWave::ActiveRecord#mount_uploader #image= should recreate versions a file
     Failure/Error: FileUtils.cp(path, new_path) unless new_path == path

     ArgumentError:
       same file: ~/carrierwave/spec/public/uploads/test.jpeg and ~/carrierwave/spec/public/uploads/test.jpeg
     # ./lib/carrierwave/sanitized_file.rb:213:in `copy!'
     # ./lib/carrierwave/sanitized_file.rb:203:in `copy_to'
     # ./lib/carrierwave/storage/file.rb:36:in `store!'
     # ./lib/carrierwave/uploader/store.rb:66:in `block in store!'
     # ./lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
     # ./lib/carrierwave/uploader/store.rb:65:in `store!'
     # ./lib/carrierwave/mounter.rb:103:in `each'
     # ./lib/carrierwave/mounter.rb:103:in `store!'
     # ./lib/carrierwave/mount.rb:435:in `store_image!'
     # ./spec/orm/activerecord_spec.rb:205:in `block (4 levels) in <top (required)>'
```

From my bug hunting I *think* there may be an issue with `uploader.store_path` missing the actual file name.  

On the initial save...
```ruby
uploader.store_path # => uploads/test.jpeg
```

But when calling `update_attribute` after `recreate_versions!`...
```ruby
uploader.store_path # =>  uploads/
```

Which results in `FileUtils.cp` getting weird paths for comparisons.

I have limited knowledge of CarrierWave internals and ran out of time trying to debug this today but wanted to record it here in case it was familiar to anyone else.
