### ISSUE TITLE
NoMethodError: private method `select' called for nil:NilClass

### ISSUE THREAD

**Issue by celsoMartins** [carrierwaveuploader/carrierwave#2675]
Hey folks.

**carrierwave 3.0.0**

I'm getting this error while trying to test invalid forms with image upload. It started to happen after the last gem update.

```
NoMethodError: private method `select' called for nil:NilClass

  0) ArticlesController authenticated as editor PUT #update with invalid data does not update the article and renders the form with errors
     Failure/Error: if @article.update(update_params.except(:featured_image).freeze)

     NoMethodError:
       private method `select' called for nil:NilClass
     # /Users/celsomartins/.rvm/gems/ruby-3.2.2@aposta10/gems/carrierwave-3.0.0/lib/carrierwave/mounter.rb:205:in `remove_added'
     # /Users/celsomartins/.rvm/gems/ruby-3.2.2@aposta10/gems/carrierwave-3.0.0/lib/carrierwave/mount.rb:400:in `remove_rolled_back_og_image'
```

The exception occurs in the ```current_paths = (@removed_uploaders + @uploaders.select(&:staged)).map(&:path)```

```
    def remove_added
      current_paths = (@removed_uploaders + @uploaders.select(&:staged)).map(&:path)
      @added_uploaders
        .reject {|uploader| current_paths.include?(uploader.path) }
        .each { |uploader| uploader.remove! }
      reset_changes!
    end
```

I'll fix the gem version to the one that was working.

Thanks.
